export 'package:flutter/material.dart';
export 'pages/principalPage.dart';
export 'utils/appbar.dart';
export 'pages/segunda_pantalla.dart';
export 'pages/tercera_patalla.dart';
export 'pages/cuarta_pantalla.dart';
export 'pages/quinta_pantalla.dart';
export 'pages/votacion_1.dart';
export 'utils/appbar_votacion.dart';
